### PR TITLE
Update BaseFragment.java

### PR DESCRIPTION
**Pull request by jayagrawal254**
## Checklist

__Common__

- [ ] I am ran the app before creating PR
- [ ] I am ran all tests before creating PR

__UI__

- [ ] I am ran the app for visual checks.

__Logic__

- [ ] I am tested basic app functionality.

## Changes

Describe all changes here:

- First;
- Second;
- Third;
- ...

## Comments

Describe all additional information here.

### CODE REVIEW

**Review by fartem — CHANGES_REQUESTED** [review]
Add PR description and check code with Checkstyle (run `gradlew check` from console).

**Comment by jayagrawal254** [comment]
Hey, should I include this files
`import org.gradle.api.Plugin; 
import org.gradle.api.Project; `

**Comment by jayagrawal254** [comment]
first I should `import org.gradle.api.Plugin; import org.gradle.api.Project;` this and run .gradlew/test. am I going right?

**Comment by fartem** [comment]
> first I should `import org.gradle.api.Plugin; import org.gradle.api.Project;` this and run .gradlew/test. am I going right?

No. Just run checks from console (or from Android Studio - in Gradle section at right find `Tasks` -> `Verification` -> `check` and run it).

**Pull request closed without merging**
