### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by jayagrawal254**
## Checklist

__Common__

- [ ] I am ran the app before creating PR
- [ ] I am ran all tests before creating PR

__UI__

- [ ] I am ran the app for visual checks.

__Logic__

- [ ] I am tested basic app functionality.

## Changes

Describe all changes here:

- First;
- Second;
- Third;
- ...

## Comments

Describe all additional information here.

I have fixed some issue

### CODE REVIEW

**Review by fartem — CHANGES_REQUESTED** [review]
App cannot builds.

You don't need to change `AppSnackbar` class because it is using in some places (not when user click to back button). In `HashCalculatorFragment` exists method `appBackClick`, you need to change app exit feature in it.

**Review by fartem — CHANGES_REQUESTED** [review]
Looks good, thanks, but:
1). Line 60 in AppSnackbar.java is broken, just delete it.
2). Move `backpressedTime` variable up to place with all variables in class and format tabs.

**Comment by jayagrawal254** [comment]
now?
please tell me if I have done something wrong. I will try my best.

**Comment by jayagrawal254** [comment]
now?

**Review by fartem — CHANGES_REQUESTED** [review]
You should correct tabs and run Checkstyle analysis by calling `gradlew check` from console from project folder. Also, you don't need to implement back callback in Settings, it should be only on the Main screen. Do not use raw strings, import text values in UI from resources.

**Pull request closed without merging**
